title: Brian Han's Story
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://tigerkin89.github.io

aux_links:
  Template Repository: https://tigerkin89.github.io
